### PR TITLE
Fix builders to allow for tablePrefix

### PR DESCRIPTION
**Pull request by mattleff**
This change allows the tablePrefix to be added properly. Sorry I don't have tests!

### CODE REVIEW

**Comment by VanTanev** [comment]
Hey @mattleff, thanks for the pull request. I will review it in the following days and let you know.

**Comment by VanTanev** [comment]
Hey, @mattleff, could you provide some more detail about the error you encountered? I want to have a proper test case before merging this.

**Comment by mattleff** [comment]
@VanTanev Sure. The issue has to do with the [`<database tablePrefix="">`](http://propelorm.org/Propel/reference/schema.html#database-element) attribute, which we are using. The `tablePrefix` should be added to all classes but not to the references of those classes. So, for example, before this patch the `addPeerBuildEqualNestRelation()` template for the `Book` model would produce the following:

``` php
/**
 * Builds a new equal nest relation between Book objects
 *
 * @param      Book|integer $object1
 * @param      Book|integer $object2
 * @param      PropelPDO $con
 */
public static function buildEqualNestBookRelation($object1, $object2, PropelPDO $con = null)
{
    ...
    $aBook = new Book();
    ...
```

If the `tablePrefix` is `DB` Propel will generate classes of `DBBook` and the `Book` class will not exist. After the patch with a prefix of `DB` we get the following:

``` php
/**
 * Builds a new equal nest relation between Book objects
 *
 * @param      DBBook|integer $object1
 * @param      DBBook|integer $object2
 * @param      PropelPDO $con
 */
public static function buildEqualNestBookRelation($object1, $object2, PropelPDO $con = null)
{
    ...
    $aBook = new DBBook();
    ...
```

Notice that the classes should be fully-qualified (`DBBook`) whereas the references would be the unprefixed name (`buildEqualNestBookRelation`).

Hopefully this makes sense! :smile:

**Comment by mattleff** [comment]
@VanTanev Just pushed another place where the class needs the class prefix. Also...sorry for the false direction: this issue is with `classPrefix` not `tablePrefix`. :disappointed: 

I found [this issue](https://github.com/propelorm/Propel/pull/28/files) which was with another behavior that didn't respect `classPrefix`. I've tried to make my changes be along the same line as @willdurand.

**Comment by VanTanev** [comment]
I am having trouble writing a test for this; Does Propel's Quick Builder ignore tablePrefix? Looking into it now.

**Comment by VanTanev** [comment]
Ah :)

I read your addendum after looking at this for an hour and wondering what I was doing wrong :)

**Comment by mattleff** [comment]
@VanTanev Yeah, sorry about that! Hopefully the test becomes simpler now. :smiley:

**Comment by VanTanev** [comment]
Where is `classPrefix` even documented? I don't see it in Propel's official documentation.

**Comment by mattleff** [comment]
[Here](http://propelorm.org/Propel/reference/buildtime-configuration) and search for `classPrefix`. Also [here](http://propelorm.org/documentation/reference/configuration-file.html) for Propel2.

**Comment by VanTanev** [comment]
Ah, it's not a schema property but a build property? Jeez....

**Comment by VanTanev** [comment]
I modified the normal tests for `classPrefix` and fixed a minor bug in query methods generation here: https://github.com/VanTanev/EqualNestBehavior/commit/d3870d91dfdc7ad540f8b1e3f7c82f9fdb59608e#diff-638b64cda3a16130c2a3d7d42da1cc78L129

**Comment by mattleff** [comment]
@VanTanev Super – really appreciate it! :+1: :grinning:

**Pull request merged**
