### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by willdurand**
Heya,

I've started a refactoring of your behavior. I will provide tests later, but for now I just moved some code to dedicated templates for readability, and used the standard structure for behaviors :)

What do you think?

William

### CODE REVIEW

**Comment by VanTanev** [comment]
Looks great so far (though I only had the time to glance over your changes).

Let me know if you need anything from me, I could have a couple of hours to spare over the weekend.

**Comment by willdurand** [comment]
well, it's not yet fully working, but we could discuss about that in the weekend

**Comment by willdurand** [comment]
Ok, now it should be fine. If you want to merge that part, it could be awesome ;)

Don't forget to add this project on packagist as well.

**Comment by VanTanev** [comment]
Holy cow multiple comments!

Merging :)

**Comment by willdurand** [comment]
@CraftyShadow heh yeah... thanks!

**Comment by willdurand** [comment]
@CraftyShadow did you register the behavior on packagist? :p

**Comment by VanTanev** [comment]
I will go over it and if it works ok will submit to packagist (probably tomorrow though)

**Comment by VanTanev** [comment]
Or if you have complete confidence, I can do it right away?

**Comment by willdurand** [comment]
It won't change anything, but it will ease my work :p
I'm not confident as there is no tests yet, but I will work a lot on this
behavior, so it makes sense to register it now. We will tag a stable
version later, and it will be fine ;)

2012/6/29 Ivan Tanev <
reply@reply.github.com

**Comment by VanTanev** [comment]
http://packagist.org/packages/craftyshadow/propel-equalnest-behavior

This is my first packagist repo, so I am not overly familiar with its workflow. How about I add you as a maintainer there and collaborator here?

**Comment by willdurand** [comment]
There is a button to add a maintainer on the page, just add "couac" I guess.
Don't forget to enable the packagist post hook too, so that it will auto
update packagist on each push.

2012/6/29 Ivan Tanev <
reply@reply.github.com

**Pull request merged**
