### PR TITLE
Use the parent PK type in the jointure table PK.

### PR DESCRIPTION
**Pull request by Martiusweb**
EqualNestBehavior only supports primary keys of type integer.

This patch creates the schema using the type of the parent primary key.

### CODE REVIEW

**Comment by VanTanev** [comment]
Could I ask you to write a small test for this?

**Comment by willdurand** [comment]
+1 for the test

**Comment by Martiusweb** [comment]
A added a commit with a test to this PR a few days ago, isn't it sufficient ?

**Comment by willdurand** [comment]
Great!

**Comment by willdurand** [comment]
Thank you so much!

**Pull request merged**
